version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
  runtime-versions:
    nodejs: 10
    commands:
      - echo Installing dependencies...
      - npm i
  build:
    commands:
      - echo Building...
      - npm start
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: /